### ISSUE TITLE
Logical error in movement of certain pieces

### ISSUE THREAD

**Issue by Vikram710** [TalhaAwan/react-chess#2]
This problem is faced by pieces which can move diagonally mainly bishop and queen.
You have used src-dest %7 or %9 to check if move is possible but it doesn't work on every case.
Assume you have a bishop which can move only on white squares on index 61. There is a black square on tile 40. 61-40 %7 is 0 so according to this the bishop jumps there randomly.
Same for queen and pawns at the end of the file

Another problem I noticed is that a 2 step moving pawn cuts anything in its destination. You should have added isDestEnemyOccupied for moving 2 paces. i guess this is the chess rule.

To make it error free you must have an array of size 120 and assign first 2 rows and the last 2 rows and the side rows as offboard and check if the path to the destination passes through the offboard if so return false.
I've added images to help you understand the problem and solution
![proper](https://user-images.githubusercontent.com/49572404/78037275-f4524400-7388-11ea-8b8a-87c65af1a86a.png)
![bishop_problem](https://user-images.githubusercontent.com/49572404/78037288-f7e5cb00-7388-11ea-8805-a6db5b5ef592.png)
![pawn_problem](https://user-images.githubusercontent.com/49572404/78037298-fae0bb80-7388-11ea-961c-0ada8a9f9997.png)
![solution](https://user-images.githubusercontent.com/49572404/78037312-fd431580-7388-11ea-8760-50326114e482.png)

**Comment by TalhaAwan** [comment]
@Vikram710 thanks for bringing this up. I'll try to take a look soon. But if you could add these improvements and send a PR, that would be great.

**Comment by AyoubEd-zz** [comment]
Hello, 
I want to point one more thing. The king can't move from a position of check to another where there is still a check.
![image](https://user-images.githubusercontent.com/20077848/83340664-4e18b100-a2db-11ea-847e-44bd998393dd.png)
![image](https://user-images.githubusercontent.com/20077848/83340693-81f3d680-a2db-11ea-8c4c-703be7e238ba.png)

**Comment by Vikram710** [comment]
i don't think he has implemented check detection at all

**Comment by TalhaAwan** [comment]
@Vikram710 true. 

@AyoubEd you could move a piece such that the king is exposed to check. This of course shouldn't happen. I mentioned that in readme under to dos for improvement.

The code is three years old, so I'd like to bring the React and other packages to the newest versions first. Then fix these logical errors. Hopefully soon!

**Comment by TalhaAwan** [comment]
@Vikram710 I have fixed the logical error you pointed out.  It was happening nearly for all pieces. Used row, col, and diagonal dictionaries to ensure no illogical jumping. Thanks for bringing it up.
